### ISSUE TITLE
Control spacing between rules

### ISSUE THREAD

**Issue by c10b10** [reworkcss/css#103]
Is there any way to fine tune the spacing between rules that results from `stringify`?

Currently, the output looks like this:

```css
.w1 { 
  width: 1em 
};

.w2 { 
  width: 2em 
};

.w3 { 
  width: 3em 
};

@media (--breakpoint-small) {
  .w1 { 
    width: 1em 
  };

  .w2 { 
    width: 2em 
  };

  .w3 { 
    width: 3em 
  };
}
```

Is there any way of making it look like this?

```css
.w1 { width: 1em };
.w2 { width: 2em };
.w3 { width: 3em };

@media (--breakpoint-small) {
  .w1-small { width: 1em };
  .w2-small { width: 2em };
  .w3-small { width: 3em };
}
```
