### ISSUE TITLE
Declaration matcher by regular expression is finishing too early.

### ISSUE THREAD

**Issue by pszczesniak** [reworkcss/css#178]
During parsing large `CSS` codebase i've noticed that in a specific case an error is thrown: 

```
missing '}'
```
to be more precise: below is an example of something that breaks it:
```css
div {
	background-image:url("data:image/svg+xml;utf8,<svg width='120' height='12' xmlns='http://www.w3.org/2000/svg' ><text style='paint-order:stroke fill; clip-path: inset(-3px);' stroke-width='13' fill='black' x='3' y='7' font-size='9px' font-family='Consolas, monospace'>TEST</text></svg>");
}
```
👇 
```
style='paint-order:stroke fill; clip-path: inset(-3px);'
```
To be precise - the last semicolon.

Problem lies in the regular expression:
https://github.com/reworkcss/css/blob/434aa1733f275a67ea700311451b98a14f8cc21a/lib/parse/index.js#L227

It ends before that semicolon which i mentioned above, here is an example:

https://regex101.com/r/NBh8Cy/1

Simplest solution is to remove that semicolon, but i won't have that ability always.
