### ISSUE TITLE
Missing support for @page selectors

### ISSUE THREAD

**Issue by necolas** [reworkcss/css#22]
Parsing:

``` css
@page :left {
  color:red;
}
```

results in `Error: @page missing '}'`

NB: it should also work for `:right`, `:first` and `:blank` but also for `:blank:first`

See: http://www.w3.org/TR/css3-page/#page-selectors

Also,

it would be great if the parser was lazy enough to accept the _named page_ syntax [princexml](http://www.princexml.com/doc/9.0/page-selectors/) uses:

``` css
@page big_table { 
    size: A4 landscape;
}
```

and also:

``` css
@page big_table, big_table2:first { 
    size: A4 landscape;
}
```

which all are valid syntax: see http://www.w3.org/TR/css3-page/#syntax-page-selector

(Moved from https://github.com/reworkcss/css-parse/issues/79)
