### ISSUE TITLE
@font-face undefined is not a function 

### ISSUE THREAD

**Issue by smykes** [reworkcss/css#45]
I'm having issues with the @font-face rule.  I took the code straight from the 'The New Bulletproof @Font-Face Syntax'

Attempting to run the following rule through the parser and I am getting 'Uncaught TypeError: undefined is not a function' inside of Base.visit.

``` css
@font-face {
    font-family: 'MyFontFamily';
    src: url('myfont-webfont.eot?#iefix') format('embedded-opentype'), 
         url('myfont-webfont.woff') format('woff'), 
         url('myfont-webfont.ttf')  format('truetype'),
         url('myfont-webfont.svg#svgFontName') format('svg');
    }
```

Any information would be very helpful.
