### ISSUE TITLE
Parse error @keyframes missing name with line break

### ISSUE THREAD

**Issue by gmetais** [reworkcss/css#61]
Hi there!

I got a parsing error on the following css:

```css
.icon-article-liste{font-size:1.18em;margin-right: .425em}@-webkit-keyframes
rotation{0%{-webkit-transform:rotate(0deg);transform:rotate(0deg)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes
rotation{0%{-webkit-transform:rotate(0deg);transform:rotate(0deg)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}
```

The error says: **@keyframes missing name**

The problem comes from the line-break after `@-webkit-keyframes` which does not match the regexp looking for the name.

Thank you
